[05-01-2018 04:59:25] [INFO] [] [] [] [inside getData function try block] 
[05-01-2018 04:59:25] [ERROR] [] [] [] [error while getting the data] 
Traceback (most recent call last):
  File "/Users/admin/Work/Face_Recognition/datalayer.py", line 22, in getData
    rows = session.execute(query=getQuery, parameters=[classId])
  File "cassandra/cluster.py", line 2122, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 2159, in cassandra.cluster.Session.execute_async
  File "cassandra/cluster.py", line 2173, in cassandra.cluster.Session._create_response_future
  File "cassandra/query.py", line 451, in cassandra.query.PreparedStatement.bind
  File "cassandra/query.py", line 576, in cassandra.query.BoundStatement.bind
  File "cassandra/cqltypes.py", line 698, in cassandra.cqltypes.UTF8Type.serialize
AttributeError: 'int' object has no attribute 'encode'
[05-01-2018 05:00:26] [INFO] [] [] [] [inside getData function try block] 
[05-01-2018 05:00:26] [ERROR] [] [] [] [error while getting the data] 
Traceback (most recent call last):
  File "/Users/admin/Work/Face_Recognition/datalayer.py", line 22, in getData
    rows = session.execute(query=getQuery, parameters=[classId])
  File "cassandra/cluster.py", line 2122, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 3982, in cassandra.cluster.ResponseFuture.result
cassandra.Unauthorized: Error from server: code=2100 [Unauthorized] message="User msgbkpusr has no SELECT permission on <table imagerecognition.name_by_class> or any of its parents"
[05-01-2018 05:02:56] [INFO] [] [] [] [inside getData function try block] 
[05-01-2018 05:02:56] [INFO] [] [] [] [inside getData function try block data fetched successfully] 
